fix(types): option privacy in Nodenext | Node16
fastify/fastify-caching pull request #137
Opened 2024-02-17 15:07 UTC by Gehbt

2024-02-17 18:22 UTC, mcollina commented
What is this fixing?

2024-02-18 10:10 UTC, Gehbt commented
> What is this fixing?

I added the informations.

2024-02-18 11:03 UTC, gurgunday commented
Can you please add a test?

We use tsd

2024-02-18 12:10 UTC, Gehbt commented
> Can you please add a test?
> 
> We use tsd
I cannot provide the test, but I can give a minimal reproduction.

2024-03-04 12:26 UTC, gurgunday requested changes
I'm not sure this change fixes the issue you're having

In fact, there seems to be no issue according to tests, [why is this passing](https://github.com/fastify/fastify-caching/blob/a3bedfac0dbc6efaa27216d1e46f8516da7285b9/types/index.test-d.ts#L10-L15)?

2024-03-04 16:06 UTC, Gehbt commented
Do you review the Reproduction? I think I have revealed it: there is using `"type": "commonjs"`, if changed to `"type": "module"` it will break. May we really ought to wait a guy in NodeNext?

2024-03-04 16:48 UTC, gurgunday approved these changes
Oh I see now, this indeed fixes the problem

Thanks

2024-03-04 16:48 UTC, gurgunday commented
Not sure how we could test this... but reproducing is possible

2024-06-27 18:44 UTC, marcoreni commented
any chance of getting this merged?

2024-07-01 10:47 UTC, mcollina approved these changes
lgtm

2024-07-01 10:47 UTC, merged